-------------------------------------------------------
-- Author:             Roger Limachi Orellana        --
-- Date Created:       2012-12-23                    --
-- Date Push:          2012-12-23                    --
-- Asunt:              Sales                         --
-------------------------------------------------------

-- CREATE A TABLE CART_ITEM IF NOT EXISTS
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[CART_ITEM]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
BEGIN
	
	CREATE TABLE [dbo].[CART_ITEM]
	(
		[ID_CART_ITEM] [int] IDENTITY(1,1) NOT NULL,
	    [ID_PRODUCT] [int] NOT NULL,
		[ID_CART] varchar(63) NOT NULL,
	    [AMOUNT_CART_ITEM] [int] NOT NULL,
	    [PRICE_CART_ITEM] decimal(18,10) NOT NULL,
	    [CREATION_CART_ITEM] [datetime] NOT NULL,
		PRIMARY KEY (ID_CART_ITEM),
		FOREIGN KEY (ID_PRODUCT) REFERENCES PRODUCT(ID_PRODUCT)
	) 

	PRINT 'CART_ITEM TABLE CREATED'
END
ELSE
BEGIN
	PRINT 'DO NOT CREATE THE CART_ITEM TABLE'
END
GO

-- CREATE COLUMN PRICE_PRODUCT IN PRODUCT TABLE IF NOT EXISTS
IF EXISTS(	SELECT * 
			FROM sys.objects  SO
			WHERE SO.TYPE = 'U' AND SO.NAME = 'PRODUCT')
BEGIN	
	IF NOT EXISTS (	SELECT * 
					FROM sys.objects  SO
					INNER JOIN sys.columns SC ON SO.OBJECT_ID = SC.OBJECT_ID
					WHERE SO.TYPE = 'U' AND SO.NAME = 'PRODUCT' AND SC.NAME = 'PRICE_PRODUCT')
	BEGIN
		ALTER TABLE PRODUCT ADD PRICE_PRODUCT DECIMAL(18, 10);
		PRINT 'CREATE COLUMN PRICE_PRODUCT IN THE PRODUCT TABLE';
	END	
	ELSE
    BEGIN
	    PRINT 'DO NOT CREATE COLUMN PRICE_PRODUCT IN THE PRODUCT TABLE'
    END	
END
GO

-- CREATE COLUMN IMAGE_URL_PRODUCT IN PRODUCT TABLE IF NOT EXISTS
IF EXISTS(	SELECT * 
			FROM sys.objects  SO
			WHERE SO.TYPE = 'U' AND SO.NAME = 'PRODUCT')
BEGIN	
	IF NOT EXISTS (	SELECT * 
					FROM sys.objects  SO
					INNER JOIN sys.columns SC ON SO.OBJECT_ID = SC.OBJECT_ID
					WHERE SO.TYPE = 'U' AND SO.NAME = 'PRODUCT' AND SC.NAME = 'IMAGE_URL_PRODUCT')
	BEGIN
		ALTER TABLE PRODUCT ADD IMAGE_URL_PRODUCT VARCHAR(255);
		PRINT 'CREATE COLUMN IMAGE_URL_PRODUCT IN THE PRODUCT TABLE';
	END	
	ELSE
    BEGIN
	    PRINT 'DO NOT CREATE COLUMN IMAGE_URL_PRODUCT IN THE PRODUCT TABLE'
    END	
END
GO
