//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Shopnet.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PURCHASE_ORDER))]
    public partial class PROVIDER: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID_PROVIDER
        {
            get { return _iD_PROVIDER; }
            set
            {
                if (_iD_PROVIDER != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID_PROVIDER' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD_PROVIDER = value;
                    OnPropertyChanged("ID_PROVIDER");
                }
            }
        }
        private int _iD_PROVIDER;
    
        [DataMember]
        public string NAME_PROVIDER
        {
            get { return _nAME_PROVIDER; }
            set
            {
                if (_nAME_PROVIDER != value)
                {
                    _nAME_PROVIDER = value;
                    OnPropertyChanged("NAME_PROVIDER");
                }
            }
        }
        private string _nAME_PROVIDER;
    
        [DataMember]
        public string DESC_PROVIDER
        {
            get { return _dESC_PROVIDER; }
            set
            {
                if (_dESC_PROVIDER != value)
                {
                    _dESC_PROVIDER = value;
                    OnPropertyChanged("DESC_PROVIDER");
                }
            }
        }
        private string _dESC_PROVIDER;
    
        [DataMember]
        public System.DateTime CREATION_PROVIDER
        {
            get { return _cREATION_PROVIDER; }
            set
            {
                if (_cREATION_PROVIDER != value)
                {
                    _cREATION_PROVIDER = value;
                    OnPropertyChanged("CREATION_PROVIDER");
                }
            }
        }
        private System.DateTime _cREATION_PROVIDER;
    
        [DataMember]
        public string ADDRESS_PROVIDER
        {
            get { return _aDDRESS_PROVIDER; }
            set
            {
                if (_aDDRESS_PROVIDER != value)
                {
                    _aDDRESS_PROVIDER = value;
                    OnPropertyChanged("ADDRESS_PROVIDER");
                }
            }
        }
        private string _aDDRESS_PROVIDER;
    
        [DataMember]
        public string PHONE_PROVIDER
        {
            get { return _pHONE_PROVIDER; }
            set
            {
                if (_pHONE_PROVIDER != value)
                {
                    _pHONE_PROVIDER = value;
                    OnPropertyChanged("PHONE_PROVIDER");
                }
            }
        }
        private string _pHONE_PROVIDER;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<PURCHASE_ORDER> PURCHASE_ORDER
        {
            get
            {
                if (_pURCHASE_ORDER == null)
                {
                    _pURCHASE_ORDER = new TrackableCollection<PURCHASE_ORDER>();
                    _pURCHASE_ORDER.CollectionChanged += FixupPURCHASE_ORDER;
                }
                return _pURCHASE_ORDER;
            }
            set
            {
                if (!ReferenceEquals(_pURCHASE_ORDER, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_pURCHASE_ORDER != null)
                    {
                        _pURCHASE_ORDER.CollectionChanged -= FixupPURCHASE_ORDER;
                    }
                    _pURCHASE_ORDER = value;
                    if (_pURCHASE_ORDER != null)
                    {
                        _pURCHASE_ORDER.CollectionChanged += FixupPURCHASE_ORDER;
                    }
                    OnNavigationPropertyChanged("PURCHASE_ORDER");
                }
            }
        }
        private TrackableCollection<PURCHASE_ORDER> _pURCHASE_ORDER;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PURCHASE_ORDER.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupPURCHASE_ORDER(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PURCHASE_ORDER item in e.NewItems)
                {
                    item.PROVIDER = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PURCHASE_ORDER", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PURCHASE_ORDER item in e.OldItems)
                {
                    if (ReferenceEquals(item.PROVIDER, this))
                    {
                        item.PROVIDER = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PURCHASE_ORDER", item);
                    }
                }
            }
        }

        #endregion
    }
}
