//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Shopnet.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Product))]
    [KnownType(typeof(PURCHASE_ORDER))]
    public partial class STOCK: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID_PRODUCT
        {
            get { return _iD_PRODUCT; }
            set
            {
                if (_iD_PRODUCT != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID_PRODUCT' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PRODUCT != null && PRODUCT.ProductID != value)
                        {
                            PRODUCT = null;
                        }
                    }
                    _iD_PRODUCT = value;
                    OnPropertyChanged("ID_PRODUCT");
                }
            }
        }
        private int _iD_PRODUCT;
    
        [DataMember]
        public int ID_PURCHASE
        {
            get { return _iD_PURCHASE; }
            set
            {
                if (_iD_PURCHASE != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID_PURCHASE' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (PURCHASE_ORDER != null && PURCHASE_ORDER.ID_PURCHASE != value)
                        {
                            PURCHASE_ORDER = null;
                        }
                    }
                    _iD_PURCHASE = value;
                    OnPropertyChanged("ID_PURCHASE");
                }
            }
        }
        private int _iD_PURCHASE;
    
        [DataMember]
        public int AMOUNT_STOCK
        {
            get { return _aMOUNT_STOCK; }
            set
            {
                if (_aMOUNT_STOCK != value)
                {
                    _aMOUNT_STOCK = value;
                    OnPropertyChanged("AMOUNT_STOCK");
                }
            }
        }
        private int _aMOUNT_STOCK;
    
        [DataMember]
        public decimal COST_STOCK
        {
            get { return _cOST_STOCK; }
            set
            {
                if (_cOST_STOCK != value)
                {
                    _cOST_STOCK = value;
                    OnPropertyChanged("COST_STOCK");
                }
            }
        }
        private decimal _cOST_STOCK;
    
        [DataMember]
        public decimal PRICE_STOCK
        {
            get { return _pRICE_STOCK; }
            set
            {
                if (_pRICE_STOCK != value)
                {
                    _pRICE_STOCK = value;
                    OnPropertyChanged("PRICE_STOCK");
                }
            }
        }
        private decimal _pRICE_STOCK;
    
        [DataMember]
        public System.DateTime CREATION_STOCK
        {
            get { return _cREATION_STOCK; }
            set
            {
                if (_cREATION_STOCK != value)
                {
                    _cREATION_STOCK = value;
                    OnPropertyChanged("CREATION_STOCK");
                }
            }
        }
        private System.DateTime _cREATION_STOCK;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public Product PRODUCT
        {
            get { return _pRODUCT; }
            set
            {
                if (!ReferenceEquals(_pRODUCT, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (ID_PRODUCT != value.ProductID)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _pRODUCT;
                    _pRODUCT = value;
                    FixupPRODUCT(previousValue);
                    OnNavigationPropertyChanged("PRODUCT");
                }
            }
        }
        private Product _pRODUCT;
    
        [DataMember]
        public PURCHASE_ORDER PURCHASE_ORDER
        {
            get { return _pURCHASE_ORDER; }
            set
            {
                if (!ReferenceEquals(_pURCHASE_ORDER, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (ID_PURCHASE != value.ID_PURCHASE)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _pURCHASE_ORDER;
                    _pURCHASE_ORDER = value;
                    FixupPURCHASE_ORDER(previousValue);
                    OnNavigationPropertyChanged("PURCHASE_ORDER");
                }
            }
        }
        private PURCHASE_ORDER _pURCHASE_ORDER;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PRODUCT = null;
            PURCHASE_ORDER = null;
        }

        #endregion
        #region Association Fixup
    
        private void FixupPRODUCT(Product previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Stocks.Contains(this))
            {
                previousValue.Stocks.Remove(this);
            }
    
            if (PRODUCT != null)
            {
                if (!PRODUCT.Stocks.Contains(this))
                {
                    PRODUCT.Stocks.Add(this);
                }
    
                ID_PRODUCT = PRODUCT.ProductID;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PRODUCT")
                    && (ChangeTracker.OriginalValues["PRODUCT"] == PRODUCT))
                {
                    ChangeTracker.OriginalValues.Remove("PRODUCT");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PRODUCT", previousValue);
                }
                if (PRODUCT != null && !PRODUCT.ChangeTracker.ChangeTrackingEnabled)
                {
                    PRODUCT.StartTracking();
                }
            }
        }
    
        private void FixupPURCHASE_ORDER(PURCHASE_ORDER previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.STOCKs.Contains(this))
            {
                previousValue.STOCKs.Remove(this);
            }
    
            if (PURCHASE_ORDER != null)
            {
                if (!PURCHASE_ORDER.STOCKs.Contains(this))
                {
                    PURCHASE_ORDER.STOCKs.Add(this);
                }
    
                ID_PURCHASE = PURCHASE_ORDER.ID_PURCHASE;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("PURCHASE_ORDER")
                    && (ChangeTracker.OriginalValues["PURCHASE_ORDER"] == PURCHASE_ORDER))
                {
                    ChangeTracker.OriginalValues.Remove("PURCHASE_ORDER");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("PURCHASE_ORDER", previousValue);
                }
                if (PURCHASE_ORDER != null && !PURCHASE_ORDER.ChangeTracker.ChangeTrackingEnabled)
                {
                    PURCHASE_ORDER.StartTracking();
                }
            }
        }

        #endregion
    }
}
