//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Shopnet.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(SaleOrder))]
    public partial class TYPE_PAYMENT: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID_TYPE_PAYMENT
        {
            get { return _iD_TYPE_PAYMENT; }
            set
            {
                if (_iD_TYPE_PAYMENT != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID_TYPE_PAYMENT' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD_TYPE_PAYMENT = value;
                    OnPropertyChanged("ID_TYPE_PAYMENT");
                }
            }
        }
        private int _iD_TYPE_PAYMENT;
    
        [DataMember]
        public string DESC_TYPE_PAYMENT
        {
            get { return _dESC_TYPE_PAYMENT; }
            set
            {
                if (_dESC_TYPE_PAYMENT != value)
                {
                    _dESC_TYPE_PAYMENT = value;
                    OnPropertyChanged("DESC_TYPE_PAYMENT");
                }
            }
        }
        private string _dESC_TYPE_PAYMENT;
    
        [DataMember]
        public int AMOUNT_TYPE_PAYMENT
        {
            get { return _aMOUNT_TYPE_PAYMENT; }
            set
            {
                if (_aMOUNT_TYPE_PAYMENT != value)
                {
                    _aMOUNT_TYPE_PAYMENT = value;
                    OnPropertyChanged("AMOUNT_TYPE_PAYMENT");
                }
            }
        }
        private int _aMOUNT_TYPE_PAYMENT;
    
        [DataMember]
        public Nullable<decimal> TOTAL_SALE_MINIMUM
        {
            get { return _tOTAL_SALE_MINIMUM; }
            set
            {
                if (_tOTAL_SALE_MINIMUM != value)
                {
                    _tOTAL_SALE_MINIMUM = value;
                    OnPropertyChanged("TOTAL_SALE_MINIMUM");
                }
            }
        }
        private Nullable<decimal> _tOTAL_SALE_MINIMUM;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<SaleOrder> SALE_ORDER
        {
            get
            {
                if (_sALE_ORDER == null)
                {
                    _sALE_ORDER = new TrackableCollection<SaleOrder>();
                    _sALE_ORDER.CollectionChanged += FixupSALE_ORDER;
                }
                return _sALE_ORDER;
            }
            set
            {
                if (!ReferenceEquals(_sALE_ORDER, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_sALE_ORDER != null)
                    {
                        _sALE_ORDER.CollectionChanged -= FixupSALE_ORDER;
                    }
                    _sALE_ORDER = value;
                    if (_sALE_ORDER != null)
                    {
                        _sALE_ORDER.CollectionChanged += FixupSALE_ORDER;
                    }
                    OnNavigationPropertyChanged("SALE_ORDER");
                }
            }
        }
        private TrackableCollection<SaleOrder> _sALE_ORDER;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            SALE_ORDER.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupSALE_ORDER(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (SaleOrder item in e.NewItems)
                {
                    item.TypePayment = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SALE_ORDER", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SaleOrder item in e.OldItems)
                {
                    if (ReferenceEquals(item.TypePayment, this))
                    {
                        item.TypePayment = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SALE_ORDER", item);
                    }
                }
            }
        }

        #endregion
    }
}
