//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace Shopnet.Models
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(PURCHASE_ORDER))]
    [KnownType(typeof(SALE_ORDER))]
    [KnownType(typeof(SESSION))]
    [KnownType(typeof(ROLE))]
    public partial class USER: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ID_USER
        {
            get { return _iD_USER; }
            set
            {
                if (_iD_USER != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ID_USER' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iD_USER = value;
                    OnPropertyChanged("ID_USER");
                }
            }
        }
        private int _iD_USER;
    
        [DataMember]
        public string NAME_USER
        {
            get { return _nAME_USER; }
            set
            {
                if (_nAME_USER != value)
                {
                    _nAME_USER = value;
                    OnPropertyChanged("NAME_USER");
                }
            }
        }
        private string _nAME_USER;
    
        [DataMember]
        public string PASSWORD_USER
        {
            get { return _pASSWORD_USER; }
            set
            {
                if (_pASSWORD_USER != value)
                {
                    _pASSWORD_USER = value;
                    OnPropertyChanged("PASSWORD_USER");
                }
            }
        }
        private string _pASSWORD_USER;
    
        [DataMember]
        public System.DateTime CREATION_USER
        {
            get { return _cREATION_USER; }
            set
            {
                if (_cREATION_USER != value)
                {
                    _cREATION_USER = value;
                    OnPropertyChanged("CREATION_USER");
                }
            }
        }
        private System.DateTime _cREATION_USER;
    
        [DataMember]
        public int STATUS_USER
        {
            get { return _sTATUS_USER; }
            set
            {
                if (_sTATUS_USER != value)
                {
                    _sTATUS_USER = value;
                    OnPropertyChanged("STATUS_USER");
                }
            }
        }
        private int _sTATUS_USER;

        #endregion
        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<PURCHASE_ORDER> PURCHASE_ORDER
        {
            get
            {
                if (_pURCHASE_ORDER == null)
                {
                    _pURCHASE_ORDER = new TrackableCollection<PURCHASE_ORDER>();
                    _pURCHASE_ORDER.CollectionChanged += FixupPURCHASE_ORDER;
                }
                return _pURCHASE_ORDER;
            }
            set
            {
                if (!ReferenceEquals(_pURCHASE_ORDER, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_pURCHASE_ORDER != null)
                    {
                        _pURCHASE_ORDER.CollectionChanged -= FixupPURCHASE_ORDER;
                    }
                    _pURCHASE_ORDER = value;
                    if (_pURCHASE_ORDER != null)
                    {
                        _pURCHASE_ORDER.CollectionChanged += FixupPURCHASE_ORDER;
                    }
                    OnNavigationPropertyChanged("PURCHASE_ORDER");
                }
            }
        }
        private TrackableCollection<PURCHASE_ORDER> _pURCHASE_ORDER;
    
        [DataMember]
        public TrackableCollection<SALE_ORDER> SALE_ORDER
        {
            get
            {
                if (_sALE_ORDER == null)
                {
                    _sALE_ORDER = new TrackableCollection<SALE_ORDER>();
                    _sALE_ORDER.CollectionChanged += FixupSALE_ORDER;
                }
                return _sALE_ORDER;
            }
            set
            {
                if (!ReferenceEquals(_sALE_ORDER, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_sALE_ORDER != null)
                    {
                        _sALE_ORDER.CollectionChanged -= FixupSALE_ORDER;
                    }
                    _sALE_ORDER = value;
                    if (_sALE_ORDER != null)
                    {
                        _sALE_ORDER.CollectionChanged += FixupSALE_ORDER;
                    }
                    OnNavigationPropertyChanged("SALE_ORDER");
                }
            }
        }
        private TrackableCollection<SALE_ORDER> _sALE_ORDER;
    
        [DataMember]
        public TrackableCollection<SESSION> SESSIONs
        {
            get
            {
                if (_sESSIONs == null)
                {
                    _sESSIONs = new TrackableCollection<SESSION>();
                    _sESSIONs.CollectionChanged += FixupSESSIONs;
                }
                return _sESSIONs;
            }
            set
            {
                if (!ReferenceEquals(_sESSIONs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_sESSIONs != null)
                    {
                        _sESSIONs.CollectionChanged -= FixupSESSIONs;
                    }
                    _sESSIONs = value;
                    if (_sESSIONs != null)
                    {
                        _sESSIONs.CollectionChanged += FixupSESSIONs;
                    }
                    OnNavigationPropertyChanged("SESSIONs");
                }
            }
        }
        private TrackableCollection<SESSION> _sESSIONs;
    
        [DataMember]
        public TrackableCollection<ROLE> ROLEs
        {
            get
            {
                if (_rOLEs == null)
                {
                    _rOLEs = new TrackableCollection<ROLE>();
                    _rOLEs.CollectionChanged += FixupROLEs;
                }
                return _rOLEs;
            }
            set
            {
                if (!ReferenceEquals(_rOLEs, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_rOLEs != null)
                    {
                        _rOLEs.CollectionChanged -= FixupROLEs;
                    }
                    _rOLEs = value;
                    if (_rOLEs != null)
                    {
                        _rOLEs.CollectionChanged += FixupROLEs;
                    }
                    OnNavigationPropertyChanged("ROLEs");
                }
            }
        }
        private TrackableCollection<ROLE> _rOLEs;

        #endregion
        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            PURCHASE_ORDER.Clear();
            SALE_ORDER.Clear();
            SESSIONs.Clear();
            ROLEs.Clear();
        }

        #endregion
        #region Association Fixup
    
        private void FixupPURCHASE_ORDER(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (PURCHASE_ORDER item in e.NewItems)
                {
                    item.USER = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("PURCHASE_ORDER", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PURCHASE_ORDER item in e.OldItems)
                {
                    if (ReferenceEquals(item.USER, this))
                    {
                        item.USER = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("PURCHASE_ORDER", item);
                    }
                }
            }
        }
    
        private void FixupSALE_ORDER(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (SALE_ORDER item in e.NewItems)
                {
                    item.USER = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SALE_ORDER", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SALE_ORDER item in e.OldItems)
                {
                    if (ReferenceEquals(item.USER, this))
                    {
                        item.USER = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SALE_ORDER", item);
                    }
                }
            }
        }
    
        private void FixupSESSIONs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (SESSION item in e.NewItems)
                {
                    item.USER = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("SESSIONs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (SESSION item in e.OldItems)
                {
                    if (ReferenceEquals(item.USER, this))
                    {
                        item.USER = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("SESSIONs", item);
                    }
                }
            }
        }
    
        private void FixupROLEs(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (ROLE item in e.NewItems)
                {
                    if (!item.USERs.Contains(this))
                    {
                        item.USERs.Add(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("ROLEs", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ROLE item in e.OldItems)
                {
                    if (item.USERs.Contains(this))
                    {
                        item.USERs.Remove(this);
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("ROLEs", item);
                    }
                }
            }
        }

        #endregion
    }
}
